version: "3.7"

volumes:
  portainer_data:
    name: portainer_data

services:
  portainer:
    build:
      context: .
      dockerfile: portainer/Dockerfile
    container_name: portainer
    restart: unless-stopped
    ports:
      - "${TUNNEL_PORT}:8000"
      - "${API_PORT}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      TZ: Asia/Jakarta
    network_mode: bridge
